version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: restaurant_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: restaurant
      MYSQL_USER: restaurant_app
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
